const {test}=require('node:test');const assert=require('node:assert/strict');
function fresh(){for(const key of Object.keys(require.cache)){if(/\/(api|lib)\//.test(key)||key.endsWith('/scripts/local-router.cjs'))delete require.cache[key];}return require('../scripts/local-router.cjs');}
async function request(handler,url,method='GET'){let status=200,body;const headers={};await handler({url,method},{set statusCode(s){status=s},setHeader(k,v){headers[k]=v},writeHead(s,h){status=s;Object.assign(headers,h)},end(b){body=b}});return {status,body,headers};}
test('dashboard has brand mark; legacy routes and stored data are absent',async()=>{const app=fresh();const root=await request(app,'/');assert.equal(root.status,200);assert.match(String(root.body),/src="\/brand.svg"/);for(const p of ['/output.json','/data/snapshot.json'])assert.equal((await request(app,p)).status,404);assert.equal((await request(app,'/brand.svg')).status,200);assert.equal((await request(app,'/','POST')).status,405);assert.equal((await request(app,'/','HEAD')).body,'');});
test('provider names, symbols, logos, quote time, nulls and history preserved; public request and cache',async()=>{delete process.env.COINGECKO_DEMO_API_KEY;const app=fresh(),original=global.fetch;let calls=0;global.fetch=async(url,options)=>{calls++;assert.match(url,/per_page=50/);assert.equal(options.headers['x-cg-demo-api-key'],undefined);return {ok:true,json:async()=>[{id:'bitcoin',name:'Bitcoin',symbol:'btc',image:'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png',current_price:123,market_cap:null,total_volume:456,market_cap_rank:1,price_change_percentage_24h:null,last_updated:'2026-09-16T12:00:00Z',sparkline_in_7d:{price:[100,110,123]}}]};};try{const r=await request(app,'/api/markets');const d=JSON.parse(r.body);assert.equal(r.status,200);assert.equal(d.coins[0].name,'Bitcoin');assert.equal(d.coins[0].symbol,'btc');assert.match(d.coins[0].image,/bitcoin.png/);assert.equal(d.coins[0].lastUpdated,'2026-09-16T12:00:00.000Z');assert.equal(d.coins[0].marketCap,null);assert.equal(d.coins[0].priceChangePercentage24h,null);assert.deepEqual(d.coins[0].sparkline7d,[100,110,123]);await request(app,'/api/markets');assert.equal(calls,1);}finally{global.fetch=original;}});
test('rate limit and connection failure return no fabricated or saved data',async()=>{const original=global.fetch;try{for(const failure of ['rate','network']){const app=fresh();global.fetch=async()=>{if(failure==='network')throw Error('fetch failed');return {ok:false,status:429}};const r=await request(app,'/api/markets'),d=JSON.parse(r.body);assert.equal(r.status,503);assert.deepEqual(d.coins,[]);assert.equal(d.mode,'unavailable');assert.ok(d.error);assert.equal(d.retrievedAt,undefined);}}finally{global.fetch=original;}});
test('API key stays in upstream headers and untrusted image URLs are removed',async()=>{const original=global.fetch;process.env.COINGECKO_DEMO_API_KEY='test-key';try{global.fetch=async(url,opts)=>{assert.equal(opts.headers['x-cg-demo-api-key'],'test-key');assert.ok(!url.includes('test-key'));return {ok:true,json:async()=>[{id:'bitcoin',name:'Bitcoin',symbol:'btc',image:'https://untrusted.example/image.svg'}]}};const r=await request(fresh(),'/api/markets');assert.equal(JSON.parse(r.body).coins[0].image,null);assert.ok(!r.body.includes('test-key'));}finally{global.fetch=original;delete process.env.COINGECKO_DEMO_API_KEY;}});

test('token uses the fast price endpoint and logs only BTC and ETH prices',async()=>{const fetchOriginal=global.fetch,logOriginal=console.log;const logs=[];let calls=0;global.fetch=async(url,options)=>{calls++;assert.match(url,/simple\/price\?ids=bitcoin,ethereum/);assert.match(url,/include_last_updated_at=true/);assert.equal(options.signal.aborted,false);return {ok:true,json:async()=>({bitcoin:{usd:100,last_updated_at:1700000000},ethereum:{usd:20,last_updated_at:1700000010}})}};console.log=(...args)=>logs.push(args);try{const app=fresh(),r=await request(app,'/token'),d=JSON.parse(r.body);assert.equal(r.status,200);assert.equal(d.mode,'live');assert.equal(d.bitcoin.price,100);assert.equal(d.bitcoin.lastUpdated,'2023-11-14T22:13:20.000Z');assert.equal(d.ethereum.price,20);assert.equal(d.currency,'USD');assert.deepEqual(logs,[['Bitcoin (BTC) price in USD:',100],['Ethereum (ETH) price in USD:',20]]);assert.equal((await request(app,'/token','HEAD')).body,'');assert.equal(logs.length,2);await request(app,'/token');assert.equal(calls,1);global.fetch=async()=>({ok:true,json:async()=>({bitcoin:{usd:100}})});const missing=await request(fresh(),'/token');assert.equal(missing.status,503);assert.ok(JSON.parse(missing.body).error);}finally{global.fetch=fetchOriginal;console.log=logOriginal;}});
test('token retains last BTC and ETH prices after an upstream failure',async()=>{const original=global.fetch;let good=true;global.fetch=async()=>good?{ok:true,json:async()=>({bitcoin:{usd:100},ethereum:{usd:20}})}:{ok:false,status:429};try{const app=fresh();assert.equal((await request(app,'/token')).status,200);good=false;const originalNow=Date.now;const now=originalNow();Date.now=()=>now+16_000;try{const r=await request(app,'/token');const data=JSON.parse(r.body);assert.equal(r.status,200);assert.equal(data.mode,'stale');assert.equal(data.bitcoin.price,100);assert.equal(data.ethereum.price,20);assert.match(data.notice,/rate limit/i);}finally{Date.now=originalNow;}}finally{global.fetch=original;}});

test('keeps the last successful market data available after an upstream failure',async()=>{const original=global.fetch;let available=true;global.fetch=async()=>available?{ok:true,json:async()=>[{id:'bitcoin',name:'Bitcoin',symbol:'btc',current_price:100},{id:'ethereum',name:'Ethereum',symbol:'eth',current_price:20}]}:{ok:false,status:429};try{const app=fresh();const first=JSON.parse((await request(app,'/api/markets')).body);assert.equal(first.mode,'live');await new Promise(resolve=>setTimeout(resolve,1));available=false;const originalDateNow=Date.now;let now=originalDateNow();Date.now=()=>now+46_000;try{const stale=await request(app,'/api/markets');const data=JSON.parse(stale.body);assert.equal(stale.status,200);assert.equal(data.mode,'stale');assert.equal(data.coins[0].currentPrice,100);assert.match(data.notice,/rate limit/i);}finally{Date.now=originalDateNow;}}finally{global.fetch=original;}});
